version: '3'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    command: jupyter lab --ip 0.0.0.0 --port 8888 --allow-root --no-browser --notebook-dir=/django --NotebookApp.token=''
    volumes:
      - .:/django
      - ./jupyter_config:/root/.jupyter
    environment:
      - DJANGO_ALLOW_ASYNC_UNSAFE="true"

  vue-app:
    build:
      context: ./vue-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./vue-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - ollama

volumes:
  ollama_data: